### ISSUE TITLE
Running the example fails.

### ISSUE THREAD

**Issue by JeroenKnoops** [niravpatel27/gh-action-spdx-sbom-generator#2]
When running the example (with same version 0.0.9) on a create-react-app application, it will fail.

Also with latest version 0.0.19 it fails.

## Source
https://github.com/JeroenKnoops/test-spdx-action/blob/spdx-sbom-generator/.github/workflows/spdx-sbom-generator.yaml

```
# SPDX-License-Identifier: Apache-2.0

name: SPDX-SBOM-GENERATOR

on:
  push:
  workflow_dispatch:

jobs:
  generate:
    name: Generate sbom file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: gh-action-spdx-sbom-generator
        uses: niravpatel27/gh-action-spdx-sbom-generator@v1.0.0
        with:
            version: '0.0.9'   
      - name: Check if sbom file generated
        run: |
          if [ ! -f "bom-go-mod.spdx" ]; then
            echo "::error::bom-go-mod.spdx is missing. Must generate using the spdx-sbom-generator cli."
            exit 1
          else
             echo "Success!"            
          fi  
```

## Workflow error
https://github.com/JeroenKnoops/test-spdx-action/pull/2/checks?check_run_id=3931752860

<img width="1527" alt="Screenshot 2021-10-18 at 21 51 18" src="https://user-images.githubusercontent.com/10019/137804891-3ce328f5-10e7-4fca-a430-27a692607e80.png">
